'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AspNetUserLogins
    Public Property LoginProvider As String
    Public Property ProviderKey As String
    Public Property ProviderDisplayName As String
    Public Property UserId As String

    Public Overridable Property AspNetUsers As AspNetUsers

End Class
