'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AspNetRoles
    Public Property Id As String
    Public Property Name As String
    Public Property NormalizedName As String
    Public Property ConcurrencyStamp As String

    Public Overridable Property AspNetRoleClaims As ICollection(Of AspNetRoleClaims) = New HashSet(Of AspNetRoleClaims)
    Public Overridable Property AspNetUsers As ICollection(Of AspNetUsers) = New HashSet(Of AspNetUsers)

End Class
