'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AspNetUserClaims
    Public Property Id As Integer
    Public Property UserId As String
    Public Property ClaimType As String
    Public Property ClaimValue As String

    Public Overridable Property AspNetUsers As AspNetUsers

End Class
